"""Connects a Telegram chat to a web account via short-lived, single-use codes.

Codes are 8 chars, generated by the logged-in user in the web dashboard and
sent to the bot. Only the SHA-256 hash is stored; codes expire in 10 minutes
and are consumed atomically, so guessing or replaying is useless.
"""

from __future__ import annotations

import hashlib
import secrets
from datetime import UTC, datetime, timedelta

from core import db
from core.logging import get_logger

logger = get_logger(__name__)

CODE_TTL = timedelta(minutes=10)


def _hash(code: str) -> str:
    return hashlib.sha256(code.encode()).hexdigest()


async def generate_link_code(user_id) -> str:
    """Create a link code for a logged-in user (shown in the web dashboard)."""
    from uuid import UUID as _UUID

    code = secrets.token_urlsafe(6)[:8].replace("-", "a").replace("_", "b").upper()
    expires = datetime.now(UTC) + CODE_TTL
    await db.create_link_code(_hash(code), _UUID(str(user_id)), expires)
    logger.info("link code generated", extra={"user_id": str(user_id)})
    return code


async def redeem_link_code(code: str, chat_id: str) -> str:
    """Link a chat to the code's owner. Raises ValueError on any failure with
    the same message (no existence leakage)."""
    user_id = await db.consume_link_code(_hash(code.strip().upper()))
    if user_id is None:
        raise ValueError("that code is invalid or expired — generate a new one")
    await _link_chat(user_id, str(chat_id))
    logger.info("telegram linked", extra={"user_id": str(user_id)})
    return str(user_id)


async def _link_chat(user_id, chat_id: str) -> None:
    """One chat links to one account; re-linking moves the chat."""
    pool = db._require_pool()
    await pool.execute(
        "INSERT INTO telegram_links (telegram_chat_id, user_id) VALUES ($1, $2) "
        "ON CONFLICT (telegram_chat_id) DO UPDATE SET user_id = EXCLUDED.user_id, "
        "linked_at = now()",
        chat_id,
        user_id,
    )


async def user_for_chat(chat_id: str) -> str | None:
    """Resolve a chat to its linked user_id, or None if unlinked."""
    row = await db._require_pool().fetchrow(
        "SELECT user_id FROM telegram_links WHERE telegram_chat_id = $1", str(chat_id)
    )
    return str(row["user_id"]) if row else None
