# Generated by Django 5.2.17 on 2026-09-30 00:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0000_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateBucket',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ActionToken',
            fields=[
                ('digest', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('onboarding', 'Onboarding'), ('recovery', 'Recovery')], max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(null=True)),
                ('epoch', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('actor', models.CharField(max_length=64)),
                ('account_id', models.CharField(max_length=64, null=True)),
                ('object_id', models.CharField(max_length=96)),
                ('action', models.CharField(max_length=48)),
                ('outcome', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('denied', 'denied'), ('failed', 'failed'), ('uncertain', 'uncertain')], max_length=16)),
                ('request_id', models.UUIDField()),
                ('native_operation_id', models.CharField(max_length=96, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['account_id', 'created_at'], name='accounts_au_account_2c5dab_idx')],
            },
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=64, null=True)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('operator', 'Internal operator'), ('service', 'Service')], max_length=16)),
                ('verified', models.BooleanField(default=False)),
                ('epoch', models.PositiveIntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tombstone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=64)),
                ('object_id', models.CharField(max_length=96)),
                ('kind', models.CharField(max_length=32)),
                ('erased_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account_id', 'object_id', 'kind'), name='retention_object')],
            },
        ),
        migrations.CreateModel(
            name='OperatorGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=64)),
                ('action', models.CharField(choices=[('invite', 'Invite'), ('suspend', 'Suspend'), ('revoke', 'Revoke'), ('audit', 'Read audit')], max_length=32)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'account_id', 'action'), name='operator_scoped_grant')],
            },
        ),
    ]
