# Generated by Django 5.2.17 on 2026-09-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_lifecycle_foundation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatorgrant',
            name='action',
            field=models.CharField(choices=[('invite', 'Invite'), ('suspend', 'Suspend'), ('revoke', 'Revoke'), ('audit', 'Read audit'), ('lifecycle_create', 'Lifecycle create'), ('lifecycle_start', 'Lifecycle start'), ('lifecycle_stop', 'Lifecycle stop'), ('lifecycle_upgrade', 'Lifecycle upgrade'), ('lifecycle_backup', 'Lifecycle backup'), ('lifecycle_restore', 'Lifecycle restore'), ('lifecycle_delete', 'Lifecycle delete')], max_length=32),
        ),
    ]
